// src/features/aquarium/fishes.ts
import type { IngredientTitle } from "@/features/kitchen/type";

export type FishRarity = "일반" | "희귀" | "에픽" | "전설";

export type FishInfo = {
  id: string;
  labelKo: string;
  cost: number;
  image: string;
  size: number; // 1.0 = 기본, >1 = 크게, <1 = 작게
  swimY: [number, number]; // 수영 높이 범위 (%): 0=수면, 100=바닥
  isWild: boolean; // 야생 여부 (상점엔 false만 노출)
  isMovable: boolean; // 움직임 여부
  ingredient: IngredientTitle; // 필요한 재료
  rarity: FishRarity; // 희귀도
  description: string; // 짧은 설명
};

/** 희귀도 → 디렉토리 매핑 */
const RARITY_DIR: Record<FishRarity, string> = {
  일반: "common",
  희귀: "rare",
  에픽: "epic",
  전설: "legend",
};

/** 희귀도별 기본 포획 확률 */
export const RARITY_CAPTURE: Record<FishRarity, number> = {
  일반: 0.4,
  희귀: 0.15,
  에픽: 0.04,
  전설: 0.01,
};

/** 물고기의 포획 확률(희귀도 기반) */
export function getCaptureProb(fish: Pick<FishInfo, "rarity">): number {
  return RARITY_CAPTURE[fish.rarity];
}

/** 이미지 경로 헬퍼 */
function img(rarity: FishRarity, filename: string) {
  return `/aquarium/${RARITY_DIR[rarity]}/${filename}`;
}

/* ──────────────────────────────────────────────────────────────────
   ① 일반 (Common)
   ────────────────────────────────────────────────────────────────── */
export const FISHES: FishInfo[] = [
  {
    id: "scalare",
    labelKo: "스칼라 물고기",
    cost: 40,
    image: img("일반", "scalare.png"),
    size: 0.8,
    swimY: [30, 65],
    isWild: false,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "일반",
    description: "온화한 성격의 소형 관상어예요.",
  },
  {
    id: "goldfish",
    labelKo: "금붕어",
    cost: 40,
    image: img("일반", "goldfish.png"),
    size: 0.8,
    swimY: [25, 55],
    isWild: false,
    isMovable: true,
    ingredient: "밀",
    rarity: "일반",
    description: "초보도 키우기 쉬운 친숙한 물고기예요.",
  },
  {
    id: "cardinalfish",
    labelKo: "열동가리돔",
    cost: 65,
    image: img("일반", "cardinalfish.png"),
    size: 0.8,
    swimY: [35, 65],
    isWild: false,
    isMovable: true,
    ingredient: "양파",
    rarity: "일반",
    description: "형광빛 줄무늬가 매력적인 작은 바닷물고기예요.",
  },
  {
    id: "mackerel",
    labelKo: "고등어",
    cost: 70,
    image: img("일반", "mackerel.png"),
    size: 1.4,
    swimY: [20, 60],
    isWild: false,
    isMovable: true,
    ingredient: "고기",
    rarity: "일반",
    description: "무리를 지어 바람처럼 헤엄치는 회유성 어류예요.",
  },
  {
    id: "guppy",
    labelKo: "구피",
    cost: 35,
    image: img("일반", "guppy.png"),
    size: 0.5,
    swimY: [30, 70],
    isWild: false,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "일반",
    description: "작지만 화려한 꼬리가 돋보이는 인기 품종이에요.",
  },
  {
    id: "stripedfish",
    labelKo: "줄무늬 물고기",
    cost: 40,
    image: img("일반", "stripedfish.png"),
    size: 0.8,
    swimY: [35, 65],
    isWild: false,
    isMovable: true,
    ingredient: "밀",
    rarity: "일반",
    description: "규칙적인 줄무늬가 운치 있는 소형 어종이에요.",
  },
  {
    id: "shellfish",
    labelKo: "조개",
    cost: 20,
    image: img("일반", "shellfish.png"),
    size: 0.8,
    swimY: [85, 100],
    isWild: false,
    isMovable: true,
    ingredient: "소금",
    rarity: "일반",
    description: "바닥에서 조용히 여과섭식을 하는 친구예요.",
  },
  {
    id: "shrimp",
    labelKo: "새우",
    cost: 40,
    image: img("일반", "shrimp.png"),
    size: 0.5,
    swimY: [75, 95],
    isWild: false,
    isMovable: true,
    ingredient: "소금",
    rarity: "일반",
    description: "청소부 역할을 톡톡히 하는 작은 갑각류예요.",
  },
  {
    id: "clownfish",
    labelKo: "흰동가리",
    cost: 50,
    image: img("일반", "clownfish.png"),
    size: 0.9,
    swimY: [35, 65],
    isWild: false,
    isMovable: true,
    ingredient: "양파",
    rarity: "일반",
    description: "말미잘과 공생하는 사랑스러운 바다의 인기스타예요.",
  },
  {
    id: "squid",
    labelKo: "오징어",
    cost: 55,
    image: img("일반", "squid.png"),
    size: 1.2,
    swimY: [45, 85],
    isWild: false,
    isMovable: true,
    ingredient: "얼음",
    rarity: "일반",
    description: "잉크를 뿜어 빠르게 사라지는 마술사예요.",
  },
  {
    id: "turtle",
    labelKo: "바다거북",
    cost: 65,
    image: img("일반", "turtle.png"),
    size: 1.3,
    swimY: [25, 65],
    isWild: false,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "일반",
    description: "느긋한 헤엄으로 수조를 유영하는 장수 아이콘이에요.",
  },
  {
    id: "jellyfish",
    labelKo: "해파리",
    cost: 65,
    image: img("일반", "jellyfish.png"),
    size: 1.1,
    swimY: [20, 70],
    isWild: false,
    isMovable: true,
    ingredient: "얼음",
    rarity: "일반",
    description: "유영이 몽환적인 젤리 같은 해양생물이죠.",
  },
  {
    id: "seahorse",
    labelKo: "해마",
    cost: 55,
    image: img("일반", "seahorse.png"),
    size: 0.6,
    swimY: [40, 85],
    isWild: false,
    isMovable: true,
    ingredient: "꿀",
    rarity: "일반",
    description: "수초에 매달려 몸을 숨기는 신비한 어종이에요.",
  },
  {
    id: "pufferfish",
    labelKo: "복어",
    cost: 75,
    image: img("일반", "pufferfish.png"),
    size: 1.0,
    swimY: [30, 70],
    isWild: false,
    isMovable: true,
    ingredient: "치즈",
    rarity: "일반",
    description: "경계하면 몸을 부풀려 스스로를 지키는 독특한 친구예요.",
  },
  {
    id: "stingray",
    labelKo: "가오리",
    cost: 85,
    image: img("일반", "stingray.png"),
    size: 1.2,
    swimY: [60, 95],
    isWild: false,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "일반",
    description: "날개짓하듯 우아하게 미끄러지는 해저의 글라이더예요.",
  },
  {
    id: "lobster",
    labelKo: "랍스타",
    cost: 75,
    image: img("일반", "lobster.png"),
    size: 0.8,
    swimY: [85, 98],
    isWild: false,
    isMovable: true,
    ingredient: "버터",
    rarity: "일반",
    description: "튼튼한 집게로 바닥을 천천히 거니는 갑각류예요.",
  },
  {
    id: "crab",
    labelKo: "게",
    cost: 38,
    image: img("일반", "crab.png"),
    size: 0.5,
    swimY: [88, 95],
    isWild: false,
    isMovable: true,
    ingredient: "케찹",
    rarity: "일반",
    description: "옆걸음으로 바닥을 청소하는 성실한 주민이에요.",
  },

  /* ────────────────────────────────────────────────────────────────
     ② 희귀 (Rare)
     ──────────────────────────────────────────────────────────────── */
  {
    id: "nautilus",
    labelKo: "암모나이트",
    cost: 85,
    image: img("희귀", "nautilus.png"),
    size: 1.0,
    swimY: [65, 95],
    isWild: true,
    isMovable: true,
    ingredient: "계란",
    rarity: "희귀",
    description: "고대의 껍질을 닮은 신비한 연체동물이에요.",
  },
  {
    id: "dolphin",
    labelKo: "돌고래",
    cost: 105,
    image: img("희귀", "dolphin.png"),
    size: 2.5,
    swimY: [10, 50],
    isWild: false,
    isMovable: true,
    ingredient: "버터",
    rarity: "희귀",
    description: "영리하고 사교적인 바다의 미소천사예요.",
  },
  {
    id: "shark",
    labelKo: "상어",
    cost: 200,
    image: img("희귀", "shark.png"),
    size: 2.5,
    swimY: [20, 80],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "희귀",
    description: "예리한 감각의 바다 최상위 포식자예요.",
  },
  {
    id: "seal",
    labelKo: "바다표범",
    cost: 150,
    image: img("희귀", "seal.png"),
    size: 2.0,
    swimY: [25, 75],
    isWild: true,
    isMovable: true,
    ingredient: "계란",
    rarity: "희귀",
    description: "유연한 몸놀림으로 바다를 헤엄치는 매끈한 사냥꾼이에요.",
  },
  {
    id: "anglerfish",
    labelKo: "초롱아귀",
    cost: 170,
    image: img("희귀", "anglerfish.png"),
    size: 1.8,
    swimY: [40, 85],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "희귀",
    description: "어둠 속을 밝히는 초롱불로 먹잇감을 유혹해요.",
  },
  {
    id: "whale",
    labelKo: "고래",
    cost: 250,
    image: img("희귀", "whale.png"),
    size: 5.0,
    swimY: [50, 55],
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "희귀",
    description: "평온한 노랫소리로 바다를 울리는 거대한 존재예요.",
  },
  {
    id: "swordfish",
    labelKo: "청새치",
    cost: 105,
    image: img("희귀", "swordfish.png"),
    size: 1.5,
    swimY: [20, 55],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "희귀",
    description: "창 같은 주둥이로 순식간에 내달리는 스프린터예요.",
  },
  {
    id: "submarine",
    labelKo: "무인 잠수함",
    cost: 200,
    image: img("희귀", "submarine.png"),
    size: 2.2,
    swimY: [15, 70],
    isWild: true,
    isMovable: true,
    ingredient: "꿀",
    rarity: "희귀",
    description: "깊은 바다를 탐사하는 기계 포식자예요.",
  },
  {
    id: "snow-crab",
    labelKo: "대게",
    cost: 130,
    image: img("희귀", "snow-crab.png"),
    size: 1.2,
    swimY: [82, 98], // 바닥 지향
    isWild: true,
    isMovable: true,
    ingredient: "양파", // 기존 분배 유지
    rarity: "희귀",
    description:
      "차갑고 깊은 바다 바닥을 걷는 대형 갑각류예요. 튼튼한 집게로 먹이를 집어 먹어요.",
  },
  {
    id: "horseshoe-crab",
    labelKo: "투구게",
    cost: 110,
    image: img("희귀", "horseshoe-crab.png"),
    size: 1.3,
    swimY: [70, 95],
    isWild: true,
    isMovable: true,
    ingredient: "플랫브레드",
    rarity: "희귀",
    description: "오래된 형태를 간직한 살아있는 화석이에요.",
  },
  {
    id: "gulper-eel",
    labelKo: "풍선장어",
    cost: 180,
    image: img("희귀", "gulper-eel.png"),
    size: 2.1,
    swimY: [84, 99],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "희귀",
    description:
      "커다란 입과 가느다란 몸으로 심해를 유영하는 신비로운 장어예요.",
  },

  {
    id: "saltwater-croc",
    labelKo: "바다악어",
    cost: 190,
    image: img("희귀", "saltwater-croc.png"),
    size: 3.0,
    swimY: [15, 55],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "희귀",
    description: "강 하구와 바다를 오가며 지배하는 강력한 파충류예요.",
  },
  {
    id: "sea-anemone",
    labelKo: "말미잘",
    cost: 100,
    image: img("희귀", "sea-anemone.png"),
    size: 1.0,
    swimY: [90, 98],
    isWild: true,
    isMovable: false,
    ingredient: "녹색채소",
    rarity: "희귀",
    description: "촉수를 흔들며 바닥에서 유영자들을 기다리는 고정 생활자예요.",
  },
  {
    id: "hammerhead",
    labelKo: "귀상어",
    cost: 175,
    image: img("희귀", "hammerhead.png"),
    size: 2.6,
    swimY: [20, 60],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "희귀",
    description: "옆으로 넓은 머리로 넓은 시야를 확보하는 독특한 상어예요.",
  },
  {
    id: "coral-reef",
    labelKo: "산호초",
    cost: 140,
    image: img("희귀", "coral-reef.png"),
    size: 1.4,
    swimY: [85, 99],
    isWild: true,
    isMovable: false,
    ingredient: "밀",
    rarity: "희귀",
    description:
      "바위와 사질 바닥에 붙어 성장하며 다양한 생물이 의지하는 서식처예요.",
  },
  {
    id: "orca",
    labelKo: "범고래",
    cost: 230,
    image: img("희귀", "orca.png"),
    size: 4.0,
    swimY: [10, 40],
    isWild: true,
    isMovable: true,
    ingredient: "얼음",
    rarity: "희귀",
    description: "지능과 협동 사냥으로 유명한 바다의 카리스마예요.",
  },
  {
    id: "titanic-wreck",
    labelKo: "타이타닉호 잔해",
    cost: 200,
    image: img("희귀", "titanic-wreck.png"),
    size: 3.2,
    swimY: [85, 95],
    isWild: true,
    isMovable: false,
    ingredient: "케찹",
    rarity: "희귀",
    description: "깊은 바다 속 역사적 잔해로 신비로움을 간직하고 있어요.",
  },
  {
    id: "apollo11-wreck",
    labelKo: "아폴로 11호 잔해",
    cost: 185,
    image: img("희귀", "apollo11-wreck.png"),
    size: 2.4,
    swimY: [85, 90],
    isWild: true,
    isMovable: false,
    ingredient: "치즈",
    rarity: "희귀",
    description: "인류의 발자취를 품은 구조물의 흔적이 바닷속에 잠들어 있어요.",
  },

  /* ────────────────────────────────────────────────────────────────
     ③ 에픽 (Epic)
     ──────────────────────────────────────────────────────────────── */
  {
    id: "ing-milk-minnow",
    labelKo: "밀크 미노우",
    cost: 460,
    image: img("에픽", "ing-milk-minnow.png"),
    size: 0.9,
    swimY: [30, 65],
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "에픽",
    description: "우윳빛 비늘이 반짝이는 부드러운 미노우예요.",
  },
  {
    id: "ing-cheese-goby",
    labelKo: "치즈 고비",
    cost: 470,
    image: img("에픽", "ing-cheese-goby.png"),
    size: 0.9,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "치즈",
    rarity: "에픽",
    description: "치즈색 반점이 귀여운 작은 바닥고기예요.",
  },
  {
    id: "ing-egg-darter",
    labelKo: "에그 다터",
    cost: 455,
    image: img("에픽", "ing-egg-darter.png"),
    size: 0.8,
    swimY: [25, 60],
    isWild: true,
    isMovable: true,
    ingredient: "계란",
    rarity: "에픽",
    description: "노른자 같은 노란색 포인트가 매력적이에요.",
  },
  {
    id: "ing-meat-pike",
    labelKo: "미트 파이크",
    cost: 495,
    image: img("에픽", "ing-meat-pike.png"),
    size: 1.3,
    swimY: [20, 55],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "에픽",
    description: "육식 본능이 강한 날렵한 포식자예요.",
  },
  {
    id: "ing-bacon-eel",
    labelKo: "베이컨 뱀장어",
    cost: 485,
    image: img("에픽", "ing-bacon-eel.png"),
    size: 1.0,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "에픽",
    description: "베이컨 향으로 유인하고 작은 물고기들을 잡아먹어요.",
  },
  {
    id: "ing-honey-snapper",
    labelKo: "허니 스내퍼",
    cost: 475,
    image: img("에픽", "ing-honey-snapper.png"),
    size: 1.0,
    swimY: [30, 65],
    isWild: true,
    isMovable: true,
    ingredient: "꿀",
    rarity: "에픽",
    description: "달빛 아래 황금빛으로 빛나는 스내퍼예요.",
  },
  {
    id: "ing-salt-sardine",
    labelKo: "솔트 사딘",
    cost: 445,
    image: img("에픽", "ing-salt-sardine.png"),
    size: 0.8,
    swimY: [50, 95],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "에픽",
    description: "바닷바람 같은 짭짤한 무늬가 포인트예요.",
  },
  {
    id: "ing-ice-carp",
    labelKo: "아이스 잉어",
    cost: 465,
    image: img("에픽", "ing-ice-carp.png"),
    size: 1.0,
    swimY: [40, 80],
    isWild: true,
    isMovable: true,
    ingredient: "얼음",
    rarity: "에픽",
    description: "서늘한 푸른 비늘이 맑게 반짝여요.",
  },
  {
    id: "ing-wheat-carp",
    labelKo: "위트 카프",
    cost: 455,
    image: img("에픽", "ing-wheat-carp.png"),
    size: 1.0,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "밀",
    rarity: "에픽",
    description: "황금빛 이삭 같은 꼬리지느러미가 특징이에요.",
  },
  {
    id: "ing-flatbread-flounder",
    labelKo: "난 가자미",
    cost: 470,
    image: img("에픽", "ing-flatbread-flounder.png"),
    size: 1.1,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "플랫브레드",
    rarity: "에픽",
    description: "납작한 몸에 따끈한 빵 무늬가 퍼져 있어요.",
  },
  {
    id: "ing-butter-perch",
    labelKo: "버터 퍼치",
    cost: 460,
    image: img("에픽", "ing-butter-perch.png"),
    size: 1.0,
    swimY: [25, 65],
    isWild: true,
    isMovable: true,
    ingredient: "버터",
    rarity: "에픽",
    description: "버터처럼 윤기 도는 노란빛이 매력적이에요.",
  },
  {
    id: "ing-ketchup-koi",
    labelKo: "케찹 코이",
    cost: 450,
    image: img("에픽", "ing-ketchup-koi.png"),
    size: 0.9,
    swimY: [25, 60],
    isWild: true,
    isMovable: true,
    ingredient: "케찹",
    rarity: "에픽",
    description: "선명한 붉은 반점이 톡톡 튀는 잉어예요.",
  },
  {
    id: "ing-onion-eel",
    labelKo: "어니언 일",
    cost: 450,
    image: img("에픽", "ing-onion-eel.png"),
    size: 1.1,
    swimY: [55, 95],
    isWild: true,
    isMovable: true,
    ingredient: "양파",
    rarity: "에픽",
    description: "새콤한 향처럼 호기심 많은 뱀장어요.",
  },
  {
    id: "ing-greens-guppy",
    labelKo: "그린스 구피",
    cost: 435,
    image: img("에픽", "ing-greens-guppy.png"),
    size: 0.6,
    swimY: [35, 75],
    isWild: true,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "에픽",
    description: "풀잎 같은 꼬리로 수초 사이를 누빕니다.",
  },
  {
    id: "ing-mango-tetra",
    labelKo: "망고 테트라",
    cost: 465,
    image: img("에픽", "ing-mango-tetra.png"),
    size: 0.9,
    swimY: [30, 65],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "에픽",
    description: "망고빛 그러데이션이 사랑스러운 소형어예요.",
  },

  /* ────────────────────────────────────────────────────────────────
     ④ 전설 (Legendary)
     ──────────────────────────────────────────────────────────────── */
  {
    id: "ghost-koi",
    labelKo: "유령 비단잉어",
    cost: 900,
    image: img("전설", "ghost-koi.png"),
    size: 1.6,
    swimY: [25, 60],
    isWild: true,
    isMovable: true,
    ingredient: "꿀",
    rarity: "전설",
    description: "수면 아래서 은은히 빛이 흐르는 신비의 잉어예요.",
  },
  {
    id: "aurora-ray",
    labelKo: "오로라 가오리",
    cost: 1050,
    image: img("전설", "aurora-ray.png"),
    size: 1.8,
    swimY: [55, 90],
    isWild: true,
    isMovable: true,
    ingredient: "얼음",
    rarity: "전설",
    description: "날개에 북극광 같은 빛무늬가 흐르는 가오리예요.",
  },
  {
    id: "nebula-octopus",
    labelKo: "성운 문어",
    cost: 980,
    image: img("전설", "nebula-octopus.png"),
    size: 1.9,
    swimY: [45, 85],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "전설",
    description: "몸에 별무리처럼 점등이 번지는 괴짜 문어예요.",
  },
  {
    id: "obsidian-gargoyle",
    labelKo: "옵시디언 가고일",
    cost: 1200,
    image: img("전설", "obsidian-gargoyle.png"),
    size: 2.2,
    swimY: [80, 85],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "전설",
    description:
      "심해 절벽을 지키는 고대의 수호자, 흑요석과 바위로 빚어진 날카로운 가고일이에요.",
  },
  {
    id: "ghost-pirate-ship",
    labelKo: "유령 해적선",
    cost: 1100,
    image: img("전설", "ghost-pirate-ship.png"),
    size: 2.0,
    swimY: [15, 50],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "전설",
    description:
      "심연을 떠도는 유령 해적선, 푸른 불꽃과 안개가 감싸는 전설의 망령선이에요.",
  },
];

export const FISH_BY_ID = Object.fromEntries(
  FISHES.map((f) => [f.id, f])
) as Record<string, FishInfo>;
