// src/features/aquarium/fishes.ts
export type FishInfo = {
  id: string;
  labelKo: string;
  cost: number;
  image: string;
  size: number; // 1.0 = 기본, >1 = 크게, <1 = 작게
  swimY: [number, number]; // 수영 높이 범위 (%): 0=수면, 100=바닥
  breedProb: number; // 교배 확률 (0~1) — 정적 할당
};

export const FISHES: FishInfo[] = [
  {
    id: "scalare",
    labelKo: "스칼라 물고기",
    cost: 40,
    image: "/aquarium/scalare.png",
    size: 0.8,
    swimY: [30, 65],
    breedProb: 0.28,
  },
  {
    id: "goldfish",
    labelKo: "금붕어",
    cost: 40,
    image: "/aquarium/goldfish.png",
    size: 0.8,
    swimY: [25, 55],
    breedProb: 0.3,
  },
  {
    id: "anglerfish",
    labelKo: "아귀",
    cost: 105,
    image: "/aquarium/anglerfish.png",
    size: 1.3,
    swimY: [70, 95],
    breedProb: 0.1,
  },
  {
    id: "nautilus",
    labelKo: "암모나이트",
    cost: 85,
    image: "/aquarium/nautilus.png",
    size: 1.0,
    swimY: [65, 95],
    breedProb: 0.14,
  },
  {
    id: "cardinalfish",
    labelKo: "열동가리돔",
    cost: 65,
    image: "/aquarium/cardinalfish.png",
    size: 0.8,
    swimY: [35, 65],
    breedProb: 0.2,
  },
  {
    id: "mackerel",
    labelKo: "고등어",
    cost: 70,
    image: "/aquarium/mackerel.png",
    size: 1.4,
    swimY: [20, 60],
    breedProb: 0.18,
  },
  {
    id: "guppy",
    labelKo: "구피",
    cost: 35,
    image: "/aquarium/guppy.png",
    size: 0.5,
    swimY: [30, 70],
    breedProb: 0.35,
  },
  {
    id: "stripedfish",
    labelKo: "줄무늬 물고기",
    cost: 40,
    image: "/aquarium/stripedfish.png",
    size: 0.8,
    swimY: [35, 65],
    breedProb: 0.28,
  },
  {
    id: "shellfish",
    labelKo: "조개",
    cost: 20,
    image: "/aquarium/shellfish.png",
    size: 0.8,
    swimY: [85, 100],
    breedProb: 0.35,
  },
  {
    id: "seaeel",
    labelKo: "바다뱀장어",
    cost: 75,
    image: "/aquarium/seaeel.png",
    size: 1.3,
    swimY: [60, 95],
    breedProb: 0.16,
  },
  {
    id: "shrimp",
    labelKo: "새우",
    cost: 40,
    image: "/aquarium/shrimp.png",
    size: 0.5,
    swimY: [75, 95],
    breedProb: 0.22,
  },
  {
    id: "clownfish",
    labelKo: "흰동가리",
    cost: 50,
    image: "/aquarium/clownfish.png",
    size: 0.9,
    swimY: [35, 65],
    breedProb: 0.24,
  },
  {
    id: "squid",
    labelKo: "오징어",
    cost: 55,
    image: "/aquarium/squid.png",
    size: 1.2,
    swimY: [45, 85],
    breedProb: 0.22,
  },
  {
    id: "turtle",
    labelKo: "바다거북",
    cost: 65,
    image: "/aquarium/turtle.png",
    size: 1.3,
    swimY: [25, 65],
    breedProb: 0.16,
  },
  {
    id: "jellyfish",
    labelKo: "해파리",
    cost: 65,
    image: "/aquarium/jellyfish.png",
    size: 1.1,
    swimY: [20, 70],
    breedProb: 0.14,
  },
  {
    id: "dolphin",
    labelKo: "돌고래",
    cost: 105,
    image: "/aquarium/dolphin.png",
    size: 2.5,
    swimY: [10, 50],
    breedProb: 0.08,
  },
  {
    id: "seahorse",
    labelKo: "해마",
    cost: 55,
    image: "/aquarium/seahorse.png",
    size: 0.6,
    swimY: [40, 85],
    breedProb: 0.26,
  },
  {
    id: "pufferfish",
    labelKo: "복어",
    cost: 75,
    image: "/aquarium/pufferfish.png",
    size: 1.0,
    swimY: [30, 70],
    breedProb: 0.16,
  },
  {
    id: "stingray",
    labelKo: "가오리",
    cost: 85,
    image: "/aquarium/stingray.png",
    size: 1.2,
    swimY: [60, 95],
    breedProb: 0.12,
  },
  {
    id: "lobster",
    labelKo: "랍스타",
    cost: 75,
    image: "/aquarium/lobster.png",
    size: 0.8,
    swimY: [75, 98],
    breedProb: 0.15,
  },
  {
    id: "shark",
    labelKo: "상어",
    cost: 160,
    image: "/aquarium/shark.png",
    size: 2.5,
    swimY: [20, 80],
    breedProb: 0.06,
  },
  {
    id: "whale",
    labelKo: "고래",
    cost: 185,
    image: "/aquarium/whale.png",
    size: 5.0,
    swimY: [50, 55],
    breedProb: 0.03,
  },
  {
    id: "swordfish",
    labelKo: "청새치",
    cost: 105,
    image: "/aquarium/swordfish.png",
    size: 1.5,
    swimY: [20, 55],
    breedProb: 0.09,
  },
  {
    id: "crab",
    labelKo: "게",
    cost: 38,
    image: "/aquarium/crab.png",
    size: 0.5,
    swimY: [75, 85],
    breedProb: 0.26,
  },
];

export const FISH_BY_ID = Object.fromEntries(FISHES.map((f) => [f.id, f]));
