// src/features/aquarium/fishes.ts
import type { IngredientTitle } from "@/features/kitchen/type";

export type FishRarity = "일반" | "희귀" | "에픽" | "전설";

export type FishInfo = {
  id: string;
  labelKo: string;
  cost: number;
  image: string;
  size: number; // 1.0 = 기본, >1 = 크게, <1 = 작게
  swimY: [number, number]; // 수영 높이 범위 (%): 0=수면, 100=바닥
  isWild: boolean; // 야생 여부 (상점엔 false만 노출)
  isMovable: boolean; // 움직임 여부
  ingredient: IngredientTitle; // 필요한 재료
  rarity: FishRarity; // 희귀도
  description: string; // 짧은 설명
};

/** 희귀도 → 디렉토리 매핑 */
const RARITY_DIR: Record<FishRarity, string> = {
  일반: "common",
  희귀: "rare",
  에픽: "epic",
  전설: "legend",
};

/** 희귀도별 기본 포획 확률 */
export const RARITY_CAPTURE: Record<FishRarity, number> = {
  일반: 0.4,
  희귀: 0.15,
  에픽: 0.04,
  전설: 0.01,
};

/** 물고기의 포획 확률(희귀도 기반) */
export function getCaptureProb(fish: Pick<FishInfo, "rarity">): number {
  return RARITY_CAPTURE[fish.rarity];
}

/** 이미지 경로 헬퍼 */
function img(rarity: FishRarity, filename: string) {
  return `/aquarium/${RARITY_DIR[rarity]}/${filename}`;
}

/* ──────────────────────────────────────────────────────────────────
   ① 일반 (Common)
   ────────────────────────────────────────────────────────────────── */
export const FISHES: FishInfo[] = [
  {
    id: "scalare",
    labelKo: "스칼라 물고기",
    cost: 40,
    image: img("일반", "scalare.png"),
    size: 0.7,
    swimY: [30, 65],
    isWild: false,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "일반",
    description: "온화한 성격의 소형 관상어예요.",
  },
  {
    id: "old-boot",
    labelKo: "오래된 장화",
    cost: 13,
    image: img("일반", "old-boot.png"),
    size: 0.4,
    swimY: [70, 95],
    isWild: false,
    isMovable: true,
    ingredient: "고기",
    rarity: "일반",
    description:
      "세월이 느껴지는 낡은 장화. 바다 밑에 가라앉아 기묘한 분위기를 풍겨요.",
  },
  {
    id: "mullet",
    labelKo: "숭어",
    cost: 33,
    image: img("일반", "mullet.png"),
    size: 0.8,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "일반",
    description: "연안과 하구에 흔한 잡어.",
  },
  {
    id: "trash-tire",
    labelKo: "고무 타이어",
    cost: 18,
    image: img("일반", "trash-tire.png"),
    size: 1.1,
    swimY: [80, 98],
    isWild: false,
    isMovable: true,
    ingredient: "양파",
    rarity: "일반",
    description: "묵직한 자동차 타이어.",
  },
  {
    id: "cutlassfish",
    labelKo: "갈치",
    cost: 90,
    image: img("일반", "cutlassfish.png"),
    size: 1.1,
    swimY: [30, 60],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "일반",
    description: "칼날처럼 은빛으로 빛나는 야행성 포식자.",
  },
  {
    id: "greenling",
    labelKo: "쥐노래미",
    cost: 95,
    image: img("일반", "greenling.png"),
    size: 0.9,
    swimY: [50, 85],
    isWild: true,
    isMovable: true,
    ingredient: "케찹",
    rarity: "일반",
    description: "점무늬가 예쁜 연안의 단단한 파이터.",
  },
  {
    id: "croaker",
    labelKo: "민어",
    cost: 85,
    image: img("일반", "croaker.png"),
    size: 1.1,
    swimY: [40, 70],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "일반",
    description: "저음의 울음소리로 바다를 흔드는 대형 어종.",
  },
  {
    id: "butterfish",
    labelKo: "병어",
    cost: 70,
    image: img("일반", "butterfish.png"),
    size: 0.95,
    swimY: [45, 70],
    isWild: true,
    isMovable: true,
    ingredient: "버터",
    rarity: "일반",
    description: "납작하고 매끈한 실루엣, 부드러운 식감으로 유명.",
  },
  {
    id: "smelt",
    labelKo: "빙어",
    cost: 66,
    image: img("일반", "smelt.png"),
    size: 0.55,
    swimY: [35, 65],
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "일반",
    description: "맑은 물을 좋아하는 작고 향긋한 어종.",
  },
  {
    id: "sandlance",
    labelKo: "까나리",
    cost: 60,
    image: img("일반", "sandlance.png"),
    size: 0.65,
    swimY: [15, 40],
    isWild: true,
    isMovable: true,
    ingredient: "꿀",
    rarity: "일반",
    description: "모래 속에 쏙 숨는 영리한 가느다란 빠른 발.",
  },
  {
    id: "parrotfish",
    labelKo: "앵무고기",
    cost: 83,
    image: img("일반", "parrotfish.png"),
    size: 1.0,
    swimY: [25, 55],
    isWild: true,
    isMovable: true,
    ingredient: "밀",
    rarity: "일반",
    description: "부리 모양 입으로 산호를 갉아먹는 컬러풀 아이콘.",
  },

  {
    id: "goldfish",
    labelKo: "금붕어",
    cost: 40,
    image: img("일반", "goldfish.png"),
    size: 0.7,
    swimY: [25, 55],
    isWild: false,
    isMovable: true,
    ingredient: "밀",
    rarity: "일반",
    description: "초보도 키우기 쉬운 친숙한 물고기예요.",
  },
  {
    id: "sea-bream",
    labelKo: "도미",
    cost: 90,
    image: img("일반", "sea-bream.png"),
    size: 1.1,
    swimY: [25, 55],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "일반",
    description:
      "은은한 분홍빛 비늘이 특징인 바다 도미. 차분하게 유영하며 바다를 물들이는 인기 있는 어종.",
  },
  {
    id: "anchovy",
    labelKo: "멸치",
    cost: 48,
    image: img("일반", "anchovy.png"),
    size: 0.5,
    swimY: [20, 50], // 수면~중층
    isWild: true,
    isMovable: true,
    ingredient: "밀",
    rarity: "일반",
    description: "무리 지어 다니며 번쩍이는 작은 회유성 어종.",
  },
  {
    id: "webfoot-octopus",
    labelKo: "쭈꾸미",
    cost: 52,
    image: img("일반", "webfoot-octopus.png"),
    size: 0.6,
    swimY: [60, 90], // 바닥 근처
    isWild: true,
    isMovable: true,
    ingredient: "버터",
    rarity: "일반",
    description: "작은 다리와 둥근 몸통, 바닥을 기어다니는 소형 문어.",
  },
  {
    id: "whelk",
    labelKo: "소라",
    cost: 48,
    image: img("일반", "whelk.png"),
    size: 0.6,
    swimY: [89, 95], // 바닥
    isWild: true,
    isMovable: false,
    ingredient: "소금",
    rarity: "일반",
    description: "소용돌이 껍데기를 가진 연체동물, 바닥에 붙어사는 성격.",
  },
  {
    id: "sea-cucumber",
    labelKo: "해삼",
    cost: 50,
    image: img("일반", "sea-cucumber.png"),
    size: 0.6,
    swimY: [80, 98], // 해저
    isWild: true,
    isMovable: false,
    ingredient: "양파",
    rarity: "일반",
    description: "저층을 기어다니며 바닥 찌꺼기를 먹는 청소부.",
  },
  {
    id: "sea-urchin",
    labelKo: "성게",
    cost: 59,
    image: img("일반", "sea-urchin.png"),
    size: 0.7,
    swimY: [88, 98], // 바닥
    isWild: true,
    isMovable: false,
    ingredient: "계란",
    rarity: "일반",
    description: "가시 돋친 구형 해양생물, 바닥에 천천히 붙어 지냄.",
  },
  {
    id: "rockfish",
    labelKo: "우럭",
    cost: 94,
    ingredient: "계란",
    rarity: "일반",
    size: 1.1,
    isWild: true,
    isMovable: true,
    image: img("일반", "rockfish.png"),
    swimY: [40, 72],
    description:
      "짙은 무늬와 둥근 눈이 특징인 우럭. 달걀의 기운을 받아 색감이 은은히 밝아졌습니다.",
  },
  {
    id: "cardinalfish",
    labelKo: "열동가리돔",
    cost: 65,
    image: img("일반", "cardinalfish.png"),
    size: 0.8,
    swimY: [35, 65],
    isWild: false,
    isMovable: true,
    ingredient: "양파",
    rarity: "일반",
    description: "형광빛 줄무늬가 매력적인 작은 바닷물고기예요.",
  },
  {
    id: "goby",
    labelKo: "망둥어",
    cost: 55,
    image: img("일반", "goby.png"),
    size: 0.8,
    swimY: [40, 70],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "일반",
    description: "작은 지느러미로 바닥 근처를 살살 헤엄치는 귀여운 어종.",
  },
  {
    id: "wrasse",
    labelKo: "놀래기",
    cost: 65,
    image: img("일반", "wrasse.png"),
    size: 1,
    swimY: [30, 60],
    isWild: true,
    isMovable: true,
    ingredient: "치즈",
    rarity: "일반",
    description: "가로 줄무늬와 선명한 색의 매력이 있는 활발한 소형 어류.",
  },
  {
    id: "chromis",
    labelKo: "청록 자리돔",
    cost: 60,
    image: img("일반", "chromis.png"),
    size: 1.2,
    swimY: [35, 60],
    isWild: false,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "일반",
    description: "맑은 청록빛 몸색과 군영 습성이 귀여운 기본 어종.",
  },
  {
    id: "horse-mackerel",
    labelKo: "전갱이",
    cost: 55,
    image: img("일반", "horse-mackerel.png"),
    size: 0.75,
    swimY: [40, 70],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "일반",
    description: "민첩한 움직임의 대표적인 회유성 소형 어종.",
  },

  {
    id: "sculpin",
    labelKo: "쏨뱅이",
    cost: 63,
    image: img("일반", "sculpin.png"),
    size: 0.9,
    swimY: [45, 70],
    isWild: true,
    isMovable: true,
    ingredient: "버터",
    rarity: "일반",
    description: "거친 윤곽과 뾰족한 지느러미가 포인트인 소형 어종.",
  },
  {
    id: "mango-jelly-bag",
    labelKo: "망고젤리 봉지",
    cost: 36,
    image: img("일반", "mango-jelly-bag.png"),
    size: 0.6,
    swimY: [25, 55],
    isWild: false,
    isMovable: true,
    ingredient: "망고",
    rarity: "일반",
    description:
      "달콤한 향기가 은은히 풍기는 망고젤리 봉지. 바닷속을 둥둥 떠다니며 의외로 눈에 잘 띄어요.",
  },
  {
    id: "squirrelfish",
    labelKo: "밤돔",
    cost: 78,
    image: img("일반", "squirrelfish.png"),
    size: 1.4,
    swimY: [35, 60],
    isWild: true,
    isMovable: true,
    ingredient: "계란",
    rarity: "일반",
    description: "큼직한 눈과 비늘 결이 살아있는 야행성 기본 어종.",
  },
  {
    id: "blenny",
    labelKo: "베도라치",
    cost: 73,
    image: img("일반", "blenny.png"),
    size: 1,
    swimY: [45, 70],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "일반",
    description: "바닥과 암초 틈을 오가며 찰싹거리듯 움직이는 소형 어종.",
  },
  {
    id: "halfbeak",
    labelKo: "학꽁치",
    cost: 90,
    image: img("일반", "halfbeak.png"),
    size: 1.7,
    swimY: [25, 45],
    isWild: true,
    isMovable: true,
    ingredient: "꿀",
    rarity: "일반",
    description: "수면 가까이를 빠르게 스치듯 유영하는 길쭉한 체형.",
  },
  {
    id: "sergeant-major",
    labelKo: "줄돔",
    cost: 85,
    image: img("일반", "sergeant-major.png"),
    size: 1.3,
    swimY: [30, 60],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "일반",
    description: "검은 가로줄이 선명한 활발한 산호초의 기본 어종.",
  },

  {
    id: "mackerel",
    labelKo: "고등어",
    cost: 70,
    image: img("일반", "mackerel.png"),
    size: 1.3,
    swimY: [20, 60],
    isWild: false,
    isMovable: true,
    ingredient: "고기",
    rarity: "일반",
    description: "무리를 지어 바람처럼 헤엄치는 회유성 어류예요.",
  },
  {
    id: "guppy",
    labelKo: "구피",
    cost: 35,
    image: img("일반", "guppy.png"),
    size: 0.4,
    swimY: [30, 70],
    isWild: false,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "일반",
    description: "작지만 화려한 꼬리가 돋보이는 인기 품종이에요.",
  },

  {
    id: "stripedfish",
    labelKo: "줄무늬 물고기",
    cost: 40,
    image: img("일반", "stripedfish.png"),
    size: 0.7,
    swimY: [35, 65],
    isWild: false,
    isMovable: true,
    ingredient: "밀",
    rarity: "일반",
    description: "규칙적인 줄무늬가 운치 있는 소형 어종이에요.",
  },
  {
    id: "shellfish",
    labelKo: "조개",
    cost: 20,
    image: img("일반", "shellfish.png"),
    size: 0.4,
    swimY: [97, 100],
    isWild: false,
    isMovable: false,
    ingredient: "소금",
    rarity: "일반",
    description: "바닥에서 조용히 여과섭식을 하는 친구예요.",
  },
  {
    id: "shrimp",
    labelKo: "새우",
    cost: 40,
    image: img("일반", "shrimp.png"),
    size: 0.5,
    swimY: [75, 95],
    isWild: false,
    isMovable: true,
    ingredient: "소금",
    rarity: "일반",
    description: "청소부 역할을 톡톡히 하는 작은 갑각류예요.",
  },
  {
    id: "clownfish",
    labelKo: "흰동가리",
    cost: 50,
    image: img("일반", "clownfish.png"),
    size: 0.8,
    swimY: [35, 65],
    isWild: false,
    isMovable: true,
    ingredient: "양파",
    rarity: "일반",
    description: "말미잘과 공생하는 사랑스러운 바다의 인기스타예요.",
  },
  {
    id: "squid",
    labelKo: "오징어",
    cost: 55,
    image: img("일반", "squid.png"),
    size: 1.1,
    swimY: [45, 85],
    isWild: false,
    isMovable: true,
    ingredient: "얼음",
    rarity: "일반",
    description: "잉크를 뿜어 빠르게 사라지는 마술사예요.",
  },
  {
    id: "turtle",
    labelKo: "바다거북",
    cost: 65,
    image: img("일반", "turtle.png"),
    size: 1.2,
    swimY: [25, 65],
    isWild: false,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "일반",
    description: "느긋한 헤엄으로 수조를 유영하는 장수 아이콘이에요.",
  },
  {
    id: "jellyfish",
    labelKo: "해파리",
    cost: 65,
    image: img("일반", "jellyfish.png"),
    size: 1.0,
    swimY: [20, 70],
    isWild: false,
    isMovable: true,
    ingredient: "얼음",
    rarity: "일반",
    description: "유영이 몽환적인 젤리 같은 해양생물이죠.",
  },
  {
    id: "milk-carton",
    labelKo: "우유곽",
    cost: 25,
    image: img("일반", "milk-carton.png"),
    size: 0.7,
    swimY: [3, 18], // 수면 근처를 둥둥 떠다니는 높이
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "일반",
    description: "바다를 떠돌다다니는 종이 우유곽이에요.",
  },
  {
    id: "oyster",
    labelKo: "굴",
    cost: 45,
    image: img("일반", "oyster.png"),
    size: 0.7,
    swimY: [88, 98], // 바닥 근처에 고정
    isWild: false,
    isMovable: false, // 부착 생활 (이동 없음)
    ingredient: "우유",
    rarity: "일반",
    description:
      "암반이나 사질 바닥에 붙어 지내는 이매패류예요. 껍질을 열고 닫으며 물을 걸러 먹어요.",
  },
  {
    id: "filefish",
    labelKo: "쥐치",
    cost: 70,
    image: img("일반", "filefish.png"),
    size: 1.1,
    swimY: [30, 70],
    isWild: false,
    isMovable: true,
    ingredient: "플랫브레드",
    rarity: "일반",
    description: "작은 입으로 암반을 살짝살짝 쪼아 먹는 온순한 어종이에요.",
  },
  {
    id: "sardine",
    labelKo: "정어리",
    cost: 50,
    image: img("일반", "sardine.png"),
    size: 0.6,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "케찹",
    rarity: "일반",
    description:
      "무리를 지어 반짝이며 헤엄치는 소형 어종이에요. 달큰한 케찹 향에 호기심이 많아요.",
  },
  {
    id: "octopus",
    labelKo: "문어",
    cost: 35,
    image: img("일반", "octopus.png"),
    size: 1.0,
    swimY: [75, 98], // 바닥 가까이 이동
    isWild: false,
    isMovable: true,
    ingredient: "버터",
    rarity: "일반",
    description: "작은 팔로 바닥을 기어 다니듯 유영하는 영리한 두족류예요.",
  },
  {
    id: "starfish", // 그대로
    labelKo: "불가사리", // ✅ 변경
    cost: 55,
    image: img("일반", "starfish.png"), // 그대로 (이미지도 바꾸려면 아래 참고)
    size: 0.6,
    swimY: [40, 75],
    isWild: false,
    isMovable: false, // ✅ 변경
    ingredient: "계란", // ✅ 변경
    rarity: "일반",
    description: "벽에 붙어 떨어지지 않아요.",
  },
  {
    id: "seaweed-pile",
    labelKo: "해조류 더미",
    cost: 23,
    image: img("일반", "seaweed-pile.png"),
    size: 0.4,
    swimY: [92, 99], // 바닥 근처 고정
    isWild: false,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "일반",
    description: "여러 겹의 해조가 폭신하게 쌓여 잔물결에 살랑거려요.",
  },
  {
    id: "seahorse",
    labelKo: "해마",
    cost: 55,
    image: img("일반", "seahorse.png"),
    size: 0.6,
    swimY: [40, 85],
    isWild: false,
    isMovable: true,
    ingredient: "꿀",
    rarity: "일반",
    description: "수초에 매달려 몸을 숨기는 신비한 어종이에요.",
  },
  {
    id: "pufferfish",
    labelKo: "복어",
    cost: 75,
    image: img("일반", "pufferfish.png"),
    size: 1.0,
    swimY: [30, 70],
    isWild: false,
    isMovable: true,
    ingredient: "치즈",
    rarity: "일반",
    description: "경계하면 몸을 부풀려 스스로를 지키는 독특한 친구예요.",
  },
  {
    id: "stingray",
    labelKo: "가오리",
    cost: 85,
    image: img("일반", "stingray.png"),
    size: 1.2,
    swimY: [60, 95],
    isWild: false,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "일반",
    description: "날개짓하듯 우아하게 미끄러지는 해저의 글라이더예요.",
  },
  {
    id: "lobster",
    labelKo: "랍스타",
    cost: 75,
    image: img("일반", "lobster.png"),
    size: 0.8,
    swimY: [85, 98],
    isWild: false,
    isMovable: true,
    ingredient: "버터",
    rarity: "일반",
    description: "튼튼한 집게로 바닥을 천천히 거니는 갑각류예요.",
  },
  {
    id: "plastic-bag",
    labelKo: "떠다니는 비닐봉지",
    cost: 10,
    image: img("일반", "plastic-bag.png"),
    size: 0.6,
    swimY: [20, 50],
    isWild: false,
    isMovable: true,
    ingredient: "밀",
    rarity: "일반",
    description:
      "바닷속에서 펄럭이며 떠다니는 비닐봉지. 보기엔 소소하지만 은근 무섭죠.",
  },
  {
    id: "crab",
    labelKo: "게",
    cost: 38,
    image: img("일반", "crab.png"),
    size: 0.5,
    swimY: [88, 95],
    isWild: false,
    isMovable: true,
    ingredient: "케찹",
    rarity: "일반",
    description: "옆걸음으로 바닥을 청소하는 성실한 주민이에요.",
  },
  {
    id: "rusty_diving_tank",
    labelKo: "녹슨 잠수통",
    cost: 30,
    image: img("일반", "rusty_diving_tank.png"),
    ingredient: "치즈",
    size: 1.4, // 덩치 있는 소품 느낌
    swimY: [10, 20], // 바닥 근처에 스폰
    isWild: false,
    isMovable: true, // 배치 이동 가능
    rarity: "일반",
    description:
      "깊은 바다 밑에 가라앉아 세월의 녹이 슨 잠수통. 가끔 작은 거품을 뿜어내요.",
  },
  {
    id: "old-anchor",
    labelKo: "낡은 닻",
    cost: 45,
    image: img("일반", "old-anchor.png"),
    size: 2.2,
    swimY: [83, 95],
    isWild: false,
    isMovable: false,
    ingredient: "꿀",
    rarity: "일반",
    description: "과거의 배에서 떨어진 닻이 바다 밑에 자리 잡고 있어요.",
  },
  {
    id: "lionfish",
    labelKo: "쏠배감펭",
    cost: 105,
    image: img("일반", "lionfish.png"),
    size: 1.5,
    swimY: [30, 60],
    isWild: true,
    isMovable: true,
    ingredient: "플랫브레드",
    rarity: "일반",
    description: "화려한 가시 지느러미가 특징인 바다의 멋진 포식자.",
  },
  {
    id: "sunfish",
    labelKo: "개복치",
    cost: 85,
    image: img("일반", "sunfish.png"),
    size: 1.6, // 커다란 체형
    swimY: [35, 65], // 중층을 천천히 유영
    isWild: true,
    isMovable: true,
    ingredient: "계란",
    rarity: "일반",
    description: "둥글넓적한 몸과 큰 지느러미로 느릿하게 떠다니는 바다의 요정.",
  },

  /* ────────────────────────────────────────────────────────────────
     ② 희귀 (Rare)
     ──────────────────────────────────────────────────────────────── */
  {
    id: "nautilus",
    labelKo: "암모나이트",
    cost: 85,
    image: img("희귀", "nautilus.png"),
    size: 1.0,
    swimY: [65, 95],
    isWild: true,
    isMovable: true,
    ingredient: "계란",
    rarity: "희귀",
    description: "고대의 껍질을 닮은 신비한 연체동물이에요.",
  },

  {
    id: "ancient_amphora_pair",
    labelKo: "고대 암포라 한쌍",
    cost: 120,
    image: img("희귀", "ancient_amphora_pair.png"),
    ingredient: "플랫브레드",
    size: 1.6,
    swimY: [82, 95],
    isWild: false,
    isMovable: false,
    rarity: "희귀",
    description:
      "반쯤 묻힌 항아리 두 개. 균열 사이로 기포가 솟고 해초가 살짝 엉켜 있습니다.",
  },
  {
    id: "stone-statue",
    labelKo: "바다 석상",
    cost: 140,
    image: img("희귀", "stone-statue.png"),
    size: 2.1,
    swimY: [85, 95],
    isWild: false,
    isMovable: false,
    ingredient: "밀",
    rarity: "희귀",
    description:
      "신비로운 석상이 바닷속에 잠겨 있어요. 마치 누군가의 유적 같아요.",
  },
  {
    id: "barreleye",
    labelKo: "바렐아이",
    cost: 195,
    image: img("희귀", "barreleye.png"),
    size: 1.2, // 소형 어종이지만 존재감 있게
    swimY: [55, 88], // 중층~심층
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "희귀",
    description:
      "유리처럼 투명한 머리 돔과 위쪽을 향한 관형 눈을 지닌 심해어. 잔잔한 녹빛 눈과 고요한 유영이 신비롭습니다.",
  },
  {
    id: "baby_whale_shark",
    labelKo: "아기 고래상어 ",
    cost: 220,
    image: img("희귀", "babay_whale_shark.png"),
    size: 2,
    ingredient: "베이컨",
    swimY: [28, 52],
    isWild: true,
    isMovable: true,
    rarity: "희귀",
    description:
      "점박이 무늬가 선명한 어린 고래상어. 느릿느릿 수면 아래를 미끄러져요.",
  },

  {
    id: "krabby_patty_secret",
    labelKo: "게살버거 비법서 ",
    cost: 150,
    image: img("희귀", "krabby_patty_secret.png"),
    size: 1.4,
    ingredient: "케찹",
    swimY: [80, 94],
    isWild: false,
    isMovable: true,
    rarity: "희귀",
    description: "물에 젖어도 안 풀리는 단단한 게살버거 비법서.",
  },
  {
    id: "poseidon-spear",
    labelKo: "포세이돈의 창",
    cost: 230,
    image: img("희귀", "poseidon-spear.png"),
    size: 2.5,
    swimY: [40, 75],
    isWild: false,
    isMovable: false,
    ingredient: "꿀",
    rarity: "희귀",
    description:
      "바다의 신 포세이돈이 사용했다는 전설의 창. 금빛 장식과 푸른빛 오라가 감돌며, 바다 생명체조차 경외하는 힘을 발산해요.",
  },

  {
    id: "captain-treasure-chest",
    labelKo: "선장의 보물상자",
    cost: 200,
    image: img("희귀", "captain-treasure-chest.png"),
    size: 2,
    swimY: [99, 99],
    isWild: true,
    isMovable: false,
    ingredient: "치즈",
    rarity: "희귀",
    description:
      "바다를 누비던 선장의 보물상자, 틈새로 금빛 반짝임이 새어 나와요.",
  },
  {
    id: "dolphin",
    labelKo: "돌고래",
    cost: 105,
    image: img("희귀", "dolphin.png"),
    size: 2.3,
    swimY: [10, 50],
    isWild: false,
    isMovable: true,
    ingredient: "버터",
    rarity: "희귀",
    description: "영리하고 사교적인 바다의 미소천사예요.",
  },
  {
    id: "shark",
    labelKo: "청상아리",
    cost: 200,
    image: img("희귀", "shark.png"),
    size: 3,
    swimY: [20, 80],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "희귀",
    description: "예리한 감각의 바다 최상위 포식자예요.",
  },
  {
    id: "great_white_shark",
    labelKo: "백상아리",
    cost: 245,
    image: img("희귀", "great_white_shark.png"),
    size: 3.5, // 크고 묵직한 체형
    swimY: [25, 55], // 중층 위주 유영
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "희귀",
    description:
      "강력한 체형과 뚜렷한 카운터셰이딩이 특징인 최상위 포식자. 느릿하지만 위압감 있는 유영을 보여요.",
  },
  {
    id: "sawshark",
    labelKo: "톱상어",
    cost: 190,
    image: img("희귀", "sawshark.png"),
    size: 2.7, // 길고 날씬한 체형
    swimY: [30, 62], // 중층을 유영
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "희귀",
    description:
      "긴 톱니 모양 주둥이와 수염(바벨)을 지닌 톱상어. 민첩하게 수면 아래를 가릅니다.",
  },

  {
    id: "seal",
    labelKo: "바다표범",
    cost: 150,
    image: img("희귀", "seal.png"),
    size: 1.5,
    swimY: [25, 75],
    isWild: true,
    isMovable: true,
    ingredient: "계란",
    rarity: "희귀",
    description: "유연한 몸놀림으로 바다를 헤엄치는 매끈한 사냥꾼이에요.",
  },
  {
    id: "anglerfish",
    labelKo: "초롱아귀",
    cost: 170,
    image: img("희귀", "anglerfish.png"),
    size: 1.4,
    swimY: [40, 85],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "희귀",
    description: "어둠 속을 밝히는 초롱불로 먹잇감을 유혹해요.",
  },
  {
    id: "giant-fish-bones",
    labelKo: "거대한 생선의 뼈",
    cost: 100,
    image: img("희귀", "giant-fish-bones.png"),
    size: 2,
    swimY: [95, 97], // 바닥 근처 고정
    isWild: false,
    isMovable: false,
    ingredient: "버터",
    rarity: "희귀",
    description: "거대한 생선의 백골. 아치형 척추와 갈비뼈가 장관을 이룹니다.",
  },
  {
    id: "sunset-damselfish",
    labelKo: "노을빛 제비고기",
    cost: 140,
    image: img("희귀", "sunset-damselfish.png"),
    size: 1.5,
    ingredient: "양파",
    swimY: [40, 68],
    isWild: true,
    isMovable: true,
    rarity: "희귀",
    description: "살구·라일락 노을 그라데이션이 옆구리에서 은은하게 번진다.",
  },
  {
    id: "manta-ray",
    labelKo: "만타가오리",
    cost: 180,
    image: img("희귀", "manta-ray.png"),
    size: 2.0, // 매우 큼
    swimY: [20, 60], // 중상층 활공
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "희귀",
    description: "거대한 날개로 바다를 미끄러지듯 활공하는 우아한 가오리.",
  },
  {
    id: "opah",
    labelKo: "달고기",
    cost: 135,
    image: img("희귀", "opah.png"),
    size: 1.4, // 원반형 중대형
    swimY: [30, 65], // 중층
    isWild: true,
    isMovable: true,
    ingredient: "치즈",
    rarity: "희귀",
    description: "둥근 원반형 몸과 붉은 지느러미가 인상적인 중층의 방랑자.",
  },
  {
    id: "crown-jellyfish",
    labelKo: "크라운 해파리",
    cost: 175,
    image: img("희귀", "crown-jellyfish.png"),
    size: 2.1, // 우산부 직경 기준
    swimY: [15, 55], // 상~중층 부유
    isWild: true,
    isMovable: true,
    ingredient: "얼음",
    rarity: "희귀",
    description: "투명한 몸에 보랏빛이 흐르는 은은한 발광의 해파리.",
  },
  {
    id: "fangtooth",
    labelKo: "송곳니물고기",
    cost: 190,
    image: img("희귀", "fangtooth.png"),
    size: 1.2,
    swimY: [65, 90],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "희귀",
    description:
      "큰 송곳니로 유명한 소형 포식자예요. 어두운 심해에서 강인한 생존력을 보여요.",
  },
  {
    id: "tripod-fish",
    labelKo: "삼각대고기",
    cost: 180,
    image: img("희귀", "tripod-fish.png"),
    size: 1.2,
    swimY: [70, 95], // 바닥 가까이 '서 있는' 스타일
    isWild: true,
    isMovable: true,
    ingredient: "녹색채소", // 요청 사항 반영
    rarity: "희귀",
    description: "긴 지느러미로 바닥에 서서 주변을 감지하는 독특한 심해어예요.",
  },
  {
    id: "turban-shell",
    labelKo: "청자고둥",
    cost: 115,
    image: img("희귀", "turban-shell.png"),
    size: 0.9,
    swimY: [89, 98], // 해저
    isWild: true,
    isMovable: false, // 거의 정적
    ingredient: "소금",
    rarity: "희귀",
    description: "두툼한 나선 껍질을 지닌 해저의 보석 같은 고둥.",
  },
  {
    id: "napoleon-wrasse",
    labelKo: "나폴레옹피시",
    cost: 150,
    image: img("희귀", "napoleon-wrasse.png"),
    size: 1.6,
    swimY: [25, 55], // 산호초 주변 중층
    isWild: true,
    isMovable: true,
    ingredient: "케찹",
    rarity: "희귀",
    description: "이마가 불룩한 산호초의 거인, 느긋하지만 위엄 있는 유영.",
  },
  {
    id: "sturgeon",
    labelKo: "철갑상어",
    cost: 155,
    image: img("희귀", "sturgeon.png"),
    size: 2,
    swimY: [50, 90], // 하층 선호
    isWild: true,
    isMovable: true,
    ingredient: "버터",
    rarity: "희귀",
    description: "갑옷 같은 비늘을 두른 고대계 어종, 묵직한 하층의 지배자.",
  },
  {
    id: "whale",
    labelKo: "고래",
    cost: 250,
    image: img("희귀", "whale.png"),
    size: 4.0,
    swimY: [50, 55],
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "희귀",
    description: "평온한 노랫소리로 바다를 울리는 거대한 존재예요.",
  },
  {
    id: "swordfish",
    labelKo: "청새치",
    cost: 105,
    image: img("희귀", "swordfish.png"),
    size: 1.4,
    swimY: [20, 55],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "희귀",
    description: "창 같은 주둥이로 순식간에 내달리는 스프린터예요.",
  },
  {
    id: "submarine",
    labelKo: "무인 잠수함",
    cost: 200,
    image: img("희귀", "submarine.png"),
    size: 2.0,
    swimY: [15, 70],
    isWild: true,
    isMovable: true,
    ingredient: "꿀",
    rarity: "희귀",
    description: "깊은 바다를 탐사하는 기계 포식자예요.",
  },
  {
    id: "abandoned-smurf-doll",
    labelKo: "버려진 스머프 인형",
    cost: 82,
    image: img("희귀", "abandoned-smurf-doll.png"), // 투명 PNG 권장
    size: 0.4, // 기본 부유물보다 약간 큼
    swimY: [30, 60], // 수중 중단~중상단에 둥둥
    isWild: false,
    isMovable: true,
    ingredient: "얼음",
    rarity: "희귀",
    description: "색이 바랜 파란 봉제 인형. 물살에 떠밀려 조용히 흔들려요.",
  },
  {
    id: "snow-crab",
    labelKo: "대게",
    cost: 130,
    image: img("희귀", "snow-crab.png"),
    size: 1.1,
    swimY: [82, 98], // 바닥 지향
    isWild: true,
    isMovable: true,
    ingredient: "양파", // 기존 분배 유지
    rarity: "희귀",
    description:
      "차갑고 깊은 바다 바닥을 걷는 대형 갑각류예요. 튼튼한 집게로 먹이를 집어 먹어요.",
  },
  {
    id: "horseshoe-crab",
    labelKo: "투구게",
    cost: 110,
    image: img("희귀", "horseshoe-crab.png"),
    size: 1.1,
    swimY: [70, 95],
    isWild: true,
    isMovable: true,
    ingredient: "플랫브레드",
    rarity: "희귀",
    description: "오래된 형태를 간직한 살아있는 화석이에요.",
  },
  {
    id: "gulper-eel",
    labelKo: "풍선장어",
    cost: 180,
    image: img("희귀", "gulper-eel.png"),
    size: 1.7,
    swimY: [84, 99],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "희귀",
    description:
      "커다란 입과 가느다란 몸으로 심해를 유영하는 신비로운 장어예요.",
  },

  {
    id: "saltwater-croc",
    labelKo: "바다악어",
    cost: 190,
    image: img("희귀", "saltwater-croc.png"),
    size: 3.5,
    swimY: [15, 55],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "희귀",
    description: "강 하구와 바다를 오가며 지배하는 강력한 파충류예요.",
  },
  {
    id: "sea-anemone",
    labelKo: "말미잘",
    cost: 100,
    image: img("희귀", "sea-anemone.png"),
    size: 1.0,
    swimY: [90, 98],
    isWild: true,
    isMovable: false,
    ingredient: "녹색채소",
    rarity: "희귀",
    description: "촉수를 흔들며 바닥에서 유영자들을 기다리는 고정 생활자예요.",
  },
  {
    id: "hammerhead",
    labelKo: "귀상어",
    cost: 175,
    image: img("희귀", "hammerhead.png"),
    size: 2.2,
    swimY: [20, 60],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "희귀",
    description: "옆으로 넓은 머리로 넓은 시야를 확보하는 독특한 상어예요.",
  },
  {
    id: "shipwreck_fragment",
    labelKo: "난파선 조각",
    cost: 120,
    image: img("희귀", "shipwreck_fragment.png"),
    size: 1.7,
    swimY: [85, 95], // 바닥 근처에 고정
    isWild: false,
    isMovable: false,
    ingredient: "플랫브레드",
    rarity: "희귀",
    description: "바닷속 깊이 가라앉아 세월의 흔적이 묻은 난파선의 일부.",
  },
  {
    id: "yellowtang",
    labelKo: "대형 옐로우탱",
    cost: 170,
    image: img("희귀", "yellowtang.png"),
    size: 2, // 일반보다 큰 스케일
    swimY: [25, 60],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "희귀",
    description:
      "햇살처럼 선명한 노란빛을 띠는 대형 옐로우탱. 산호초의 보물 같은 존재.",
  },
  {
    id: "coral-reef",
    labelKo: "산호초",
    cost: 140,
    image: img("희귀", "coral-reef.png"),
    size: 1.3,
    swimY: [85, 99],
    isWild: true,
    isMovable: false,
    ingredient: "밀",
    rarity: "희귀",
    description:
      "바위와 사질 바닥에 붙어 성장하며 다양한 생물이 의지하는 서식처예요.",
  },
  {
    id: "orca",
    labelKo: "범고래",
    cost: 230,
    image: img("희귀", "orca.png"),
    size: 3.0,
    swimY: [10, 40],
    isWild: true,
    isMovable: true,
    ingredient: "얼음",
    rarity: "희귀",
    description: "지능과 협동 사냥으로 유명한 바다의 카리스마예요.",
  },
  {
    id: "titanic-wreck",
    labelKo: "타이타닉호 잔해",
    cost: 200,
    image: img("희귀", "titanic-wreck.png"),
    size: 2.8,
    swimY: [92, 95],
    isWild: true,
    isMovable: false,
    ingredient: "케찹",
    rarity: "희귀",
    description: "깊은 바다 속 역사적 잔해로 신비로움을 간직하고 있어요.",
  },
  {
    id: "apollo11-wreck",
    labelKo: "아폴로 11호 잔해",
    cost: 185,
    image: img("희귀", "apollo11-wreck.png"),
    size: 2.8,
    swimY: [99, 99],
    isWild: true,
    isMovable: false,
    ingredient: "치즈",
    rarity: "희귀",
    description: "인류의 발자취를 품은 구조물의 흔적이 바닷속에 잠들어 있어요.",
  },

  /* ────────────────────────────────────────────────────────────────
     ③ 에픽 (Epic)
     ──────────────────────────────────────────────────────────────── */
  {
    id: "giant_squid",
    labelKo: "대왕오징어",
    cost: 490,
    image: img("에픽", "giant_squid.png"),
    size: 3,
    swimY: [58, 86],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "에픽",
    description:
      "길게 늘어진 촉수와 은은히 빛나는 빨판으로 유영하는 대왕오징어. 깊은 수역을 느릿하게 가로질러요.",
  },
  {
    id: "diver-kuromi",
    labelKo: "잠수부 쿠로미",
    cost: 560,
    image: img("에픽", "diver-kuromi.png"),
    size: 1.8,
    swimY: [28, 62],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "에픽",
    description:
      "버블을 뿜으며 유영하는 잠수부 쿠로미! 심해 탐험 장비와 장난기 넘치는 표정이 포인트예요.",
  },
  {
    id: "diver-kkaekooki",
    labelKo: "잠수부 록구리",
    cost: 550,
    image: img("에픽", "diver-kkaekooki.png"),
    size: 1.4,
    swimY: [25, 65], // 중층을 여유롭게 탐험
    isWild: false,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "에픽",
    description:
      "스노클과 잠수복을 장착한 깨국이가 물속을 탐험해요. 보기만 해도 기분 좋아지는 마스코트!",
  },
  {
    id: "ing-milk-minnow",
    labelKo: "밀크 미노우",
    cost: 460,
    image: img("에픽", "ing-milk-minnow.png"),
    size: 1.2,
    swimY: [30, 65],
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "에픽",
    description: "우윳빛 비늘이 반짝이는 부드러운 미노우예요.",
  },
  {
    id: "ing-cheese-goby",
    labelKo: "치즈 고비",
    cost: 470,
    image: img("에픽", "ing-cheese-goby.png"),
    size: 1.2,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "치즈",
    rarity: "에픽",
    description: "치즈색 반점이 귀여운 작은 바닥고기예요.",
  },
  {
    id: "ing-egg-darter",
    labelKo: "에그 다터",
    cost: 455,
    image: img("에픽", "ing-egg-darter.png"),
    size: 1.2,
    swimY: [25, 60],
    isWild: true,
    isMovable: true,
    ingredient: "계란",
    rarity: "에픽",
    description: "노른자 같은 노란색 포인트가 매력적이에요.",
  },
  {
    id: "ing-meat-pike",
    labelKo: "미트 파이크",
    cost: 495,
    image: img("에픽", "ing-meat-pike.png"),
    size: 2.4,
    swimY: [20, 55],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "에픽",
    description: "육식 본능이 강한 날렵한 포식자예요.",
  },
  {
    id: "ing-bacon-eel",
    labelKo: "베이컨 뱀장어",
    cost: 485,
    image: img("에픽", "ing-bacon-eel.png"),
    size: 1.2,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "에픽",
    description: "베이컨 향으로 유인하고 작은 물고기들을 잡아먹어요.",
  },
  {
    id: "ing-honey-snapper",
    labelKo: "허니 스내퍼",
    cost: 475,
    image: img("에픽", "ing-honey-snapper.png"),
    size: 1.2,
    swimY: [30, 65],
    isWild: true,
    isMovable: true,
    ingredient: "꿀",
    rarity: "에픽",
    description: "달빛 아래 황금빛으로 빛나는 스내퍼예요.",
  },
  {
    id: "ing-salt-sardine",
    labelKo: "솔트 사딘",
    cost: 445,
    image: img("에픽", "ing-salt-sardine.png"),
    size: 1.2,
    swimY: [50, 95],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "에픽",
    description: "바닷바람 같은 짭짤한 무늬가 포인트예요.",
  },
  {
    id: "ing-ice-carp",
    labelKo: "아이스 잉어",
    cost: 465,
    image: img("에픽", "ing-ice-carp.png"),
    size: 1.2,
    swimY: [40, 80],
    isWild: true,
    isMovable: true,
    ingredient: "얼음",
    rarity: "에픽",
    description: "서늘한 푸른 비늘이 맑게 반짝여요.",
  },
  {
    id: "ing-wheat-carp",
    labelKo: "위트 카프",
    cost: 455,
    image: img("에픽", "ing-wheat-carp.png"),
    size: 1.2,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "밀",
    rarity: "에픽",
    description: "황금빛 이삭 같은 꼬리지느러미가 특징이에요.",
  },
  {
    id: "ing-flatbread-flounder",
    labelKo: "난 가자미",
    cost: 470,
    image: img("에픽", "ing-flatbread-flounder.png"),
    size: 1.3,
    swimY: [35, 70],
    isWild: true,
    isMovable: true,
    ingredient: "플랫브레드",
    rarity: "에픽",
    description: "납작한 몸에 따끈한 빵 무늬가 퍼져 있어요.",
  },
  {
    id: "ing-butter-perch",
    labelKo: "버터 퍼치",
    cost: 460,
    image: img("에픽", "ing-butter-perch.png"),
    size: 1.4,
    swimY: [25, 65],
    isWild: true,
    isMovable: true,
    ingredient: "버터",
    rarity: "에픽",
    description: "버터처럼 윤기 도는 노란빛이 매력적이에요.",
  },
  {
    id: "ing-ketchup-koi",
    labelKo: "케찹 코이",
    cost: 450,
    image: img("에픽", "ing-ketchup-koi.png"),
    size: 1.2,
    swimY: [25, 60],
    isWild: true,
    isMovable: true,
    ingredient: "케찹",
    rarity: "에픽",
    description: "선명한 붉은 반점이 톡톡 튀는 잉어예요.",
  },
  {
    id: "ing-onion-eel",
    labelKo: "어니언 일",
    cost: 450,
    image: img("에픽", "ing-onion-eel.png"),
    size: 1.2,
    swimY: [55, 95],
    isWild: true,
    isMovable: true,
    ingredient: "양파",
    rarity: "에픽",
    description: "새콤한 향처럼 호기심 많은 뱀장어요.",
  },
  {
    id: "adult_whale_shark",
    labelKo: "성체 고래상어",
    cost: 440,
    image: img("에픽", "adult_whale_shark.png"),
    size: 3, // 거대한 체형
    swimY: [20, 50], // 수면 아래~중층 유영
    isWild: true,
    isMovable: true,
    ingredient: "플랫브레드",
    rarity: "에픽",
    description:
      "인디고 등과 은빛 점·줄무늬가 별자리처럼 반짝이는 거대한 여과섭식자. 고요하고 신비로운 유영을 보여요.",
  },
  {
    id: "ing-greens-guppy",
    labelKo: "그린스 구피",
    cost: 435,
    image: img("에픽", "ing-greens-guppy.png"),
    size: 1.2,
    swimY: [35, 75],
    isWild: true,
    isMovable: true,
    ingredient: "녹색채소",
    rarity: "에픽",
    description: "풀잎 같은 꼬리로 수초 사이를 누빕니다.",
  },
  {
    id: "ing-mango-tetra",
    labelKo: "망고 테트라",
    cost: 465,
    image: img("에픽", "ing-mango-tetra.png"),
    size: 1.2,
    swimY: [30, 65],
    isWild: true,
    isMovable: true,
    ingredient: "망고",
    rarity: "에픽",
    description: "망고빛 그러데이션이 사랑스러운 소형어예요.",
  },
  {
    id: "lumineil",
    labelKo: "루미네일피시",
    cost: 420,
    image: img("에픽", "lumineil-fish.png"),
    size: 2.1,
    swimY: [30, 70], // 부드럽게 유영
    isWild: false,
    isMovable: true,
    ingredient: "우유",
    rarity: "에픽",
    description:
      "투명한 몸과 빛나는 꼬리 지느러미를 가진 희귀 어종. 물속에서 은은한 빛 점이 반짝여요.",
  },

  {
    id: "aquarose",
    labelKo: "아쿠아로즈",
    cost: 480,
    image: img("에픽", "aqua-rose.png"),
    size: 2.0,
    swimY: [35, 75], // 꽃잎처럼 퍼지며 헤엄
    isWild: false,
    isMovable: true,
    ingredient: "케찹",
    rarity: "에픽",
    description:
      "장미꽃잎 같은 지느러미를 가진 아름다운 물고기. 마치 꽃이 물속에서 피어난 듯 우아해요.",
  },

  {
    id: "seraphish",
    labelKo: "세라피쉬",
    cost: 450,
    image: img("에픽", "seraphish.png"),
    size: 2.3,
    swimY: [20, 60], // 성스러운 느낌으로 천천히 이동
    isWild: false,
    isMovable: true,
    ingredient: "얼음",
    rarity: "에픽",
    description:
      "천사의 날개와 빛의 고리를 두른 신비로운 어종. 은빛 지느러미 끝에서 작은 별빛이 흩날려요.",
  },

  /* ────────────────────────────────────────────────────────────────
     ④ 전설 (Legendary)
     ──────────────────────────────────────────────────────────────── */
  {
    id: "ghost-koi",
    labelKo: "유령 비단잉어",
    cost: 900,
    image: img("전설", "ghost-koi.png"),
    size: 1.8,
    swimY: [25, 60],
    isWild: true,
    isMovable: true,
    ingredient: "우유",
    rarity: "전설",
    description: "수면 아래서 은은히 빛이 흐르는 신비의 잉어예요.",
  },
  {
    id: "aurora-ray",
    labelKo: "오로라 가오리",
    cost: 1050,
    image: img("전설", "aurora-ray.png"),
    size: 2,
    swimY: [55, 90],
    isWild: true,
    isMovable: true,
    ingredient: "얼음",
    rarity: "전설",
    description: "날개에 북극광 같은 빛무늬가 흐르는 가오리예요.",
  },
  {
    id: "nebula-octopus",
    labelKo: "성운 문어",
    cost: 980,
    image: img("전설", "nebula-octopus.png"),
    size: 2,
    swimY: [45, 85],
    isWild: true,
    isMovable: true,
    ingredient: "소금",
    rarity: "전설",
    description: "몸에 별무리처럼 점등이 번지는 괴짜 문어예요.",
  },
  {
    id: "obsidian-gargoyle",
    labelKo: "옵시디언 가고일",
    cost: 1380,
    image: img("전설", "obsidian-gargoyle.png"),
    size: 2.2,
    swimY: [80, 85],
    isWild: true,
    isMovable: true,
    ingredient: "베이컨",
    rarity: "전설",
    description:
      "심해 절벽을 지키는 고대의 수호자, 흑요석과 바위로 빚어진 날카로운 가고일이에요.",
  },
  {
    id: "abyssal-leviathan",
    labelKo: "심연의 레비아탄",
    cost: 1400,
    image: img("전설", "abyssal-leviathan.png"),
    size: 3,
    swimY: [10, 45],
    isWild: true,
    isMovable: true,
    ingredient: "고기",
    rarity: "전설",
    description:
      "눈 대신 발광공이 별자리처럼 빛나며 심연을 누비는 전설의 거상이에요.",
  },
  {
    id: "ghost-pirate-ship",
    labelKo: "유령 해적선",
    cost: 1100,
    image: img("전설", "ghost-pirate-ship.png"),
    size: 3.2,
    swimY: [15, 50],
    isWild: true,
    isMovable: true,
    ingredient: "치즈",
    rarity: "전설",
    description:
      "심연을 떠도는 유령 해적선, 푸른 불꽃과 안개가 감싸는 전설의 망령선이에요.",
  },
  {
    id: "golden_whale_choir",
    labelKo: "황금 고래 성가대",
    cost: 1260,
    image: img("전설", "golden_whale_choir.png"),
    size: 3, // 전설급: 화면을 크게 차지
    swimY: [18, 46], // 수면 아래~중층 사이를 장엄하게 유영
    isWild: true,
    isMovable: true,
    ingredient: "꿀",
    rarity: "전설",
    description:
      "합창하듯 저주파음을 내는 영물 고래. 몸통에 흐르는 금빛 문양이 노랫결에 맞춰 은은히 밝아집니다.",
  },
  {
    id: "heras-mango-tree",
    labelKo: "헤라의 망고나무",
    cost: 1280,
    image: img("전설", "heras-mango-tree.png"),
    size: 3.4,
    swimY: [89, 95],
    isWild: true,
    isMovable: false,
    ingredient: "망고",
    rarity: "전설",
    description:
      "신들의 여왕 헤라가 바다에 내려 심었다는 전설의 망고나무. 황금빛 열매에서 신성한 향기가 퍼져나와, 바다의 수호와 풍요를 상징해요.",
  },

  {
    id: "magma-megalodon",
    labelKo: "마그마 메갈로돈",
    cost: 1360,
    image: img("전설", "magma-megalodon.png"),
    size: 3.8,
    swimY: [25, 65],
    isWild: true,
    isMovable: true,
    ingredient: "케찹",
    rarity: "전설",
    description:
      "용암처럼 붉게 타오르는 전설의 메갈로돈. 지느러미와 이빨에서 불길한 붉은빛이 새어나오며, 바닷속 심연을 지배하는 존재예요.",
  },

  {
    id: "peach_coral_dragon",
    labelKo: "살구빛 산호 용",
    cost: 1240,
    image: img("전설", "peach_coral_dragon.png"),
    size: 3.2, // 길고 유려한 전설급 실루엣
    swimY: [24, 58], // 수면 아래~중층을 장엄하게 유영
    isWild: true,
    isMovable: true,
    ingredient: "양파",
    rarity: "전설",
    description:
      "살구빛·코랄 톤의 산호 가지 뿔과 프릴을 지닌 해룡. 유영에 맞춰 비늘 틈의 금빛 무늬가 은은히 맥동합니다.",
  },
  {
    id: "atlantis_last_colossus",
    labelKo: "아틀란티스 마지막 수호병",
    cost: 1370,
    image: img("전설", "atlantis_last_colossus.png"),
    size: 3, // 전설급 존재감
    swimY: [70, 95], // 해저 근처에 정지/유영
    isWild: true, // 인공 구조물 계열
    isMovable: true, // 미세한 부유/광휘 모션
    ingredient: "계란",
    rarity: "전설",
    description:
      "청록빛 파티나가 흐르는 고대 수호 골렘. 금빛 룬이 맥동하며, 삼지창과 방패로 성소를 지킨다.",
  },
];

export const FISH_BY_ID = Object.fromEntries(
  FISHES.map((f) => [f.id, f])
) as Record<string, FishInfo>;
